wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: huggingface
    huggingface_version: 4.2.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1653506850
    t:
      1:
      - 1
      - 11
      - 53
      - 55
      2:
      - 1
      - 11
      - 53
      - 55
      3:
      - 13
      4: 3.8.0
      5: 0.12.16
      6: 4.2.1
      8:
      - 3
      - 5
